In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:secret@localhost:5432/spotify_db')

query = "SELECT * FROM artists LIMIT 5;"
df_artists = pd.read_sql(query, engine)

df_artists.head()

    id         name
0  907       Future
1  908  Nicki Minaj
2  909  The Carters
3  910        Drake
4  911         Tems

In [2]:
import pandas as pd

# Υπολογισμός ωρών ακρόασης ανά καλλιτέχνη από τη βάση σου
query_top_artists = """
    SELECT 
        a.name AS artist_name, 
        ROUND(SUM(s.ms_played) / 3600000.0, 2) AS hours_played
    FROM streams s
    JOIN song_artists sa ON s.song_id = sa.song_id
    JOIN artists a ON sa.artist_id = a.id
    WHERE sa.is_feature = FALSE
    GROUP BY a.name
    ORDER BY hours_played DESC
    LIMIT 10;
"""

df_top_artists = pd.read_sql(query_top_artists, engine)
df_top_artists

     artist_name  hours_played
0          Drake        320.32
1         Future        170.25
2    Nicki Minaj        146.08
3     The Weeknd        133.76
4   Travis Scott        109.15
5  Justin Bieber         72.04
6      Lil Wayne         66.56
7        Rihanna         64.48
8  PARTYNEXTDOOR         62.05
9       Lil Tjay         53.94